[workspace]
resolver = "2"
members = [
    "crates/watchdog-core",
    "crates/watchdog-server",
    "examples/*",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
watchdog-core = { path = "crates/watchdog-core" }
watchdog-server = { path = "crates/watchdog-server" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1