[workspace]
resolver = "2"
members = [
    "watchdog",
    "watchdog-server",
    "watchdog-arxiv",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
watchdog = { path = "watchdog" }
watchdog-server = { path = "watchdog-server" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1