[workspace]
resolver = "2"
members = [
    "subscription-framework-lib",
    "subscription-server-bin",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
subscription-framework = { path = "subscription-framework-lib" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1